#!/usr/bin/env bash
#
# shellcheck disable=SC2034
BLACK='\033[30m'
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
CYAN='\033[36m'
WHITE='\033[37m'
GRAY='\033[2m'
DEFAULT='\033[0m'

export readonly LOG_COLOR_DEFAULT="${DEFAULT}"
export readonly LOG_COLOR_DEBUG="${GRAY}"
export readonly LOG_COLOR_INFO="${MAGENTA}"
export readonly LOG_COLOR_WARN="${YELLOW}"
export readonly LOG_COLOR_ERROR="${RED}"
export readonly LOG_COLOR_SUCCESS="${GREEN}"

log(){
    # pass in color, level, and message
    local color="$1" level="$2"
    printf "%b[%s] %s%b\n" "${color}" "${level}" "${*:3}" "${LOG_COLOR_DEFAULT}"
}

msg(){
    log "$LOG_COLOR_DEFAULT" "MSG" "${@}"
}

debug(){
    log "$LOG_COLOR_DEBUG" "DEBUG" "${@}"
}

info(){
    log "$LOG_COLOR_INFO" "INFO" "${@}"
}

warn(){
    log "$LOG_COLOR_WARN" "WARN" "${@}" >&2
}

error(){
    log "$LOG_COLOR_ERROR" "ERROR" "${@}" >&2
}

success(){
    log "$LOG_COLOR_SUCCESS" "SUCCESS" "${@}"
}
